### ISSUE TITLE
[BUG] dss_plugin installation of zipped plugin doesn't work

### ISSUE THREAD

**Issue by Auratons** [dataiku/dataiku-ansible-modules#11]
We were not able to install zipped plugins by the ansible module (checked even with guys from Dataiku).

```
dss_plugin:
    api_key: <personal api key>
    port: <port>
    zip_file: <local path to zip>
    state: present
    plugin_id: <id>
```

We tried several ways of zipping our plugin (zip, tar, MacOS UI) -- all of them were installable from Dataiku UI by clicking, but none of them was installable by the Ansible module. It eventually ends with Java exception that says nothing.
